# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='', max_length=500),
        ),
    ]
