# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
