# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171016_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
