# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deactivation_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
