# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171102_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
