# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20171110_1547'),
        ('courses', '0011_auto_20171113_1854'),
    ]

    operations = [
    ]
